# Análisis EDA

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../Data/job_descriptions.csv')

In [6]:
data.head(6)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."
5,116831420231957,4 to 12 Years,MCA,$59K-$93K,Brussels,Belgium,50.5039,4.4699,Full-Time,23196,...,(973)791-5355x52199,Software Tester,Quality Assurance Analyst,Snagajob,A Quality Assurance Analyst tests software and...,"{'Life and Disability Insurance, Stock Options...",Quality assurance processes Testing methodolog...,Test software applications and systems to iden...,Adani Ports and Special Economic Zone,"{""Sector"":""Infrastructure"",""Industry"":""Ports a..."

In [10]:
def transform_experience(experience):
    # Split the range and calculate the average
    min_exp, max_exp = experience.split(' to ')
    max_exp = max_exp.replace('Years', '').strip()

    return (int(min_exp) + int(max_exp)) / 2

# Apply the transformation to the "Experience" column
data['Experience_2'] = data['Experience'].apply(transform_experience)
print(data['Experience_2'].head())

0    10.0
1     7.0
2     6.0
3     7.5
4     6.5
Name: Experience_2, dtype: float64

In [8]:
unique_experience_values = data["Experience"].unique()
print(unique_experience_values)

['5 to 15 Years' '2 to 12 Years' '0 to 12 Years' '4 to 11 Years'
 '1 to 12 Years' '4 to 12 Years' '3 to 15 Years' '2 to 8 Years'
 '2 to 9 Years' '1 to 10 Years' '3 to 10 Years' '1 to 8 Years'
 '1 to 9 Years' '5 to 14 Years' '0 to 11 Years' '3 to 12 Years'
 '5 to 9 Years' '0 to 15 Years' '0 to 10 Years' '2 to 14 Years'
 '3 to 9 Years' '4 to 15 Years' '2 to 10 Years' '4 to 8 Years'
 '3 to 8 Years' '1 to 14 Years' '1 to 13 Years' '0 to 8 Years'
 '5 to 10 Years' '2 to 13 Years' '4 to 9 Years' '1 to 15 Years'
 '4 to 10 Years' '5 to 12 Years' '0 to 13 Years' '4 to 14 Years'
 '1 to 11 Years' '4 to 13 Years' '0 to 9 Years' '5 to 8 Years'
 '2 to 15 Years' '5 to 13 Years' '5 to 11 Years' '0 to 14 Years'
 '3 to 13 Years' '2 to 11 Years' '3 to 11 Years' '3 to 14 Years']

# Análisis de características

Tabla caracteristicas

| #  | Column            | Non-Null Count    | Dtype   |
|----|-------------------|-------------------|---------|
| 0  | Job Id            | 1615940 non-null  | int64   |
| 1  | Experience        | 1615940 non-null  | object  |
| 2  | Qualifications    | 1615940 non-null  | object  |
| 3  | Salary Range      | 1615940 non-null  | object  |
| 4  | location          | 1615940 non-null  | object  |
| 5  | Country           | 1615940 non-null  | object  |
| 6  | latitude          | 1615940 non-null  | float64 |
| 7  | longitude         | 1615940 non-null  | float64 |
| 8  | Work Type         | 1615940 non-null  | object  |
| 9  | Company Size      | 1615940 non-null  | int64   |
| 10 | Job Posting Date  | 1615940 non-null  | object  |
| 11 | Preference        | 1615940 non-null  | object  |
| 12 | Contact Person    | 1615940 non-null  | object  |
| 13 | Contact           | 1615940 non-null  | object  |
| 14 | Job Title         | 1615940 non-null  | object  |
| 15 | Role              | 1615940 non-null  | object  |
| 16 | Job Portal        | 1615940 non-null  | object  |
| 17 | Job Description   | 1615940 non-null  | object  |
| 18 | Benefits          | 1615940 non-null  | object  |
| 19 | skills            | 1615940 non-null  | object  |
| 20 | Responsibilities  | 1615940 non-null  | object  |
| 21 | Company           | 1615940 non-null  | object  |
| 22 | Company Profile   | 1610462 non-null  | object  |

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1615940 non-null  int64
 1   Experience        1615940 non-null  object
 2   Qualifications    1615940 non-null  object
 3   Salary Range      1615940 non-null  object
 4   location          1615940 non-null  object
 5   Country           1615940 non-null  object
 6   latitude          1615940 non-null  float64
 7   longitude         1615940 non-null  float64
 8   Work Type         1615940 non-null  object
 9   Company Size      1615940 non-null  int64
 10  Job Posting Date  1615940 non-null  object
 11  Preference        1615940 non-null  object
 12  Contact Person    1615940 non-null  object
 13  Contact           1615940 non-null  object
 14  Job Title         1615940 non-null  object
 15  Role              1615940 non-null  object
 16  Job Portal        1615940 non-null  object
 17  Job Description   1615940 non-null  object
 18  Benefits          1615940 non-null  object
 19  skills            1615940 non-null  object
 20  Responsibilities  1615940 non-null  object
 21  Company           1615940 non-null  object
 22  Company Profile   1610462 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 283.6+ MB

In [14]:
data.isnull().sum()

Job Id                 0
Experience             0
Qualifications         0
Salary Range           0
location               0
Country                0
latitude               0
longitude              0
Work Type              0
Company Size           0
Job Posting Date       0
Preference             0
Contact Person         0
Contact                0
Job Title              0
Role                   0
Job Portal             0
Job Description        0
Benefits               0
skills                 0
Responsibilities       0
Company                0
Company Profile     5478
dtype: int64